#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"IQUploaderDeferred", {PERSISTENT, JSON}},
    {"BackupManagerK3_CreateBackup", {CLEAR_ON_MANAGER_START, BOOL}},
    {"BackupManagerK3_RestoreVersion", {CLEAR_ON_MANAGER_START, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CanLiveStreaming", {CLEAR_ON_MANAGER_START, BOOL}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL, "0"}},
    {"UpdaterInstallMode", {PERSISTENT, STRING, "download_and_install"}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DevicePowerState", {CLEAR_ON_MANAGER_START, STRING}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FastSleep", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitAuthBlob", {PERSISTENT, BYTES}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"HephaestusdPid", {PERSISTENT, INT}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsLiveStreaming", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"JoystickAolRequest", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"Konn3ktSshKeys", {PERSISTENT, STRING}},
    {"Konn3ktBleTransportEnabled", {PERSISTENT, BOOL, "1"}},
    {"LanguageSetting", {PERSISTENT, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LivestreamEncoderBitrate", {CLEAR_ON_MANAGER_START | DONT_LOG, INT}},
    {"LivestreamRequestKeyframe", {CLEAR_ON_MANAGER_START | DONT_LOG, BOOL}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LateralManeuverFilter", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_EgpuNotDetected", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_EgpuFansObstructed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_EgpuOverheated", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_EgpuPcieUnavailable", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_EgpuUncompiled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_EgpuUpdateFailed", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_EgpuUsbSlow", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_StorageMissing", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},
    {"DashcamEnabled", {PERSISTENT, BOOL, "1"}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"IQSteerEffortArc", {PERSISTENT, BOOL, "0"}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UsbStorageEnabled", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    // --- iqpilot params --- //
    {"ApiCache_DriveStats", {PERSISTENT, JSON}},
    {"WideCamFaulty", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IQLaneChangeBsmDelay", {PERSISTENT, BOOL, "0"}},
    {"IQLaneChangeTimer", {PERSISTENT, INT, "0"}},
    {"NavExitLaneChange", {PERSISTENT, BOOL, "0"}},
    {"IQBlinkerMinLateralSpeed", {PERSISTENT, INT, "20"}},  // MPH or km/h
    {"IQBlinkerPauseLateral", {PERSISTENT, INT, "0"}},
    {"Brightness", {PERSISTENT, INT, "0"}},
    {"CarList", {PERSISTENT, JSON}},
    {"IQCarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"IQCarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"IQCarParamsPersistent", {PERSISTENT, BYTES}},
    {"IQCarParamsPersistentV2", {PERSISTENT, BYTES}},
    {"CarPlatformBundle", {PERSISTENT, JSON}},
    {"Konn3ktVwOdometers", {PERSISTENT, JSON}},
    {"Konn3ktVehicleOdometers", {PERSISTENT, JSON}},
    {"IQLeadReadouts", {PERSISTENT, INT, "4"}},
    {"DeviceBootMode", {PERSISTENT, INT, "0"}},
    {"IQDevUIInfo", {PERSISTENT, INT, "0"}},
    {"EnableEsimProvisioning", {PERSISTENT, BOOL, "1"}},
    {"EndToEndAlert", {PERSISTENT, BOOL, "0"}},
    {"InteractivityTimeout", {PERSISTENT, INT, "0"}},
    {"IsDevelopmentBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsReleaseIqBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"LastGPSPositionIQLoc", {PERSISTENT, STRING}},
    {"EndToEndLeadAlert", {PERSISTENT, BOOL, "0"}},
    {"LongIncrementsEnabled", {PERSISTENT, BOOL, "0"}},
    {"LongIncrementTapStep", {PERSISTENT, INT, "1"}},
    {"LongIncrementHoldStep", {PERSISTENT, INT, "5"}},
    {"IQE2ESetSpeedMode", {PERSISTENT, INT, "0"}},
    {"IQE2ESetSpeedUseCurrent", {PERSISTENT, BOOL, "0"}},
    {"IQE2ESetSpeedMph", {PERSISTENT, INT, "65"}},
    {"expSpeedConv", {PERSISTENT, BOOL, "0"}},
    {"MaxTimeOffroad", {PERSISTENT, INT, "1800"}},
    {"NightMode", {PERSISTENT, BOOL, "0"}},
    {"newLeadMpc", {PERSISTENT, BOOL, "1"}},
    {"ModelRunnerTypeCache", {CLEAR_ON_ONROAD_TRANSITION, INT}},
    {"ForceOnroadUntil", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, INT, "0"}},
    {"IQAlwaysOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IQBenchIgnition", {PERSISTENT, BOOL, "0"}},
    {"Offroad_TiciSupport", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadScreenOffBrightness", {PERSISTENT, INT, "0"}},
    {"OnroadScreenOffTimer", {PERSISTENT, INT, "15"}},
    {"OnScreenNavigation", {PERSISTENT, BOOL, "0"}},
    {"OnlineOSMaps", {PERSISTENT, BOOL, "1"}},
    {"OfflineOSMaps", {PERSISTENT, BOOL, "0"}},
    {"OSMapsStyleMode", {PERSISTENT, INT, "0"}},
    {"OSMapsHeadingUp", {PERSISTENT, BOOL, "1"}},
    {"OfflineTilesBaseUrl", {PERSISTENT, STRING}},
    {"OnroadUploads", {PERSISTENT, BOOL, "1"}},
    {"IQAutoUnits", {PERSISTENT, BOOL, "1"}},
    {"IQAutoUnitsRegion", {PERSISTENT, STRING}},
    {"IQAlertSilence", {PERSISTENT, BOOL, "0"}},
    {"IQAccelMeter", {PERSISTENT, BOOL, "0"}},
    {"IQBlinkerIndicators", {PERSISTENT, BOOL, "0"}},
    {"StandstillTimer", {PERSISTENT, BOOL, "0"}},
    // AOL (Always On Lateral) params
    {"AolEnabled", {PERSISTENT, BOOL, "1"}},
    {"AolMainCruiseAllowed", {PERSISTENT, BOOL, "1"}},
    {"AolPauseOnSteeringOverride", {PERSISTENT, BOOL, "0"}},
    {"AolSteeringMode", {PERSISTENT, INT, "0"}},
    {"AolUnifiedEngagementMode", {PERSISTENT, BOOL, "1"}},

    // Model Manager params
    {"ModelManager_ActiveBundle", {PERSISTENT, JSON}},
    {"ModelManager_ClearCache", {CLEAR_ON_MANAGER_START, BOOL}},
    {"ModelManager_DownloadIndex", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, INT, "-1"}},
    {"ModelManager_PendingIndex", {PERSISTENT, INT, "-1"}},
    {"IQModelFavorites", {PERSISTENT, STRING}},
    {"ModelManager_LastSyncTime", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, INT, "0"}},
    {"ModelManager_ModelsCache", {PERSISTENT, JSON}},

    {"IQEmacEnabled", {PERSISTENT, BOOL, "0"}},
    {"IQEmacHost", {PERSISTENT, STRING}},
    {"IQEmacModel", {PERSISTENT, STRING}},
    {"IQEmacCatalogCache", {PERSISTENT, STRING}},
    {"MacModelDownloadProgress", {CLEAR_ON_MANAGER_START, STRING, "1.0"}},
    {"MacModelStatus", {CLEAR_ON_MANAGER_START, STRING}},
    {"MacModelPresent", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelReachable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelReady", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelActive", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelFault", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelFailed", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelLastError", {CLEAR_ON_MANAGER_START, STRING}},
    {"MacModelLatencyMs", {CLEAR_ON_MANAGER_START, FLOAT, "0.0"}},

    // comma USB eGPU big-model backend. Mutually exclusive with eMac at
    // runtime (eMac wins). UsbGpu* naming/flags mirror comma's handover branch
    {"IQEgpuEnabled", {PERSISTENT, BOOL, "0"}},
    {"IQEgpuDisabled", {PERSISTENT, BOOL, "0"}},
    {"UsbGpuPresent", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"UsbGpuCompiled", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"UsbGpuReady", {PERSISTENT, BOOL, "0"}},
    {"UsbGpuLoading", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"UsbGpuActive", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"UsbGpuFailed", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"UsbGpuLastError", {CLEAR_ON_MANAGER_START, STRING}},
    {"UsbGpuLatencyMs", {CLEAR_ON_MANAGER_START, FLOAT, "0.0"}},
    {"UsbGpuStatus", {CLEAR_ON_MANAGER_START, STRING}},
    {"UsbGpuSetupProgress", {CLEAR_ON_MANAGER_START, STRING, "1.0"}},

    // Neural Network Feed Forward
    {"NeuralNetworkFeedForward", {PERSISTENT, BOOL, "0"}},

    // Backup Manager params
    {"BackupManager_CreateBackup", {PERSISTENT, BOOL}},
    {"BackupManager_RestoreVersion", {PERSISTENT, STRING}},

    // iqpilot car specific params
    {"IQHyundaiLongTune", {PERSISTENT, INT, "0"}},
    {"AutoCruiseControl", {PERSISTENT, INT, "0"}},
    {"AutoEngage", {PERSISTENT, INT, "0"}},
    {"CanfdDebug", {PERSISTENT, INT, "0"}},
    {"CanfdHDA2", {PERSISTENT, INT, "0"}},
    {"CarrotCruiseAtcDecel", {PERSISTENT, INT, "-1"}},
    {"CarrotCruiseDecel", {PERSISTENT, INT, "-1"}},
    {"CruiseButtonTest1", {PERSISTENT, INT, "8"}},
    {"CruiseButtonTest2", {PERSISTENT, INT, "30"}},
    {"CruiseButtonTest3", {PERSISTENT, INT, "1"}},
    {"CustomSteerDeltaDown", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaDownLC", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaUp", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaUpLC", {PERSISTENT, INT, "0"}},
    {"CustomSteerMax", {PERSISTENT, INT, "0"}},
    {"EnableCornerRadar", {PERSISTENT, INT, "0"}},
    {"EnableRadarTracks", {PERSISTENT, INT, "0"}},
    {"EnableRadarTracksResult", {PERSISTENT | CLEAR_ON_MANAGER_START, INT}},
    {"FingerPrints", {PERSISTENT | CLEAR_ON_MANAGER_START, STRING}},
    {"HDPuse", {PERSISTENT, INT, "0"}},
    {"HapticFeedbackWhenSpeedCamera", {PERSISTENT, INT, "0"}},
    {"HyundaiCameraSCC", {PERSISTENT, INT, "0"}},
    {"IsLdwsCar", {PERSISTENT, INT, "0"}},
    {"LaneLineCheck", {PERSISTENT, INT, "0"}},
    {"LongitudinalPersonalityMax", {PERSISTENT, INT, "3"}},
    {"MaxAngleFrames", {PERSISTENT, INT, "89"}},
    {"SpeedFromPCM", {PERSISTENT, INT, "2"}},
    {"IQSubaruCreepAssist", {PERSISTENT, BOOL, "0"}},
    {"IQSubaruCreepAssistManualBrake", {PERSISTENT, BOOL, "0"}},
    {"IQTeslaTorqueBlend", {PERSISTENT, BOOL, "0"}},
    {"IQTeslaFsdVisualization", {PERSISTENT, BOOL, "0"}},
    {"IQToyotaFactoryLong", {PERSISTENT, BOOL, "0"}},
    {"VwPqEpsPatched", {PERSISTENT, BOOL}},
    {"ToyotaSnGHack", {PERSISTENT, BOOL, "0"}},
    {"pqhca5or7Toggle", {PERSISTENT, BOOL, "1"}},
    {"iqMqbAccResume", {PERSISTENT, BOOL, "0"}},
    {"iqMqbSteeringLockout", {PERSISTENT, BOOL, "0"}},
    {"AllowLateralWhenLongUnavailable", {PERSISTENT, BOOL}},
    {"IQEmacEnabled", {PERSISTENT, BOOL, "0"}},
    {"IQEmacHost", {PERSISTENT, STRING}},
    {"IQEmacModel", {PERSISTENT, STRING}},
    {"IQEmacCatalogCache", {PERSISTENT, JSON}},
    {"IQEgpuDisabled", {PERSISTENT, BOOL, "0"}},
    {"IQEgpuEnabled", {PERSISTENT, BOOL, "0"}},
    {"MacModelStatus", {CLEAR_ON_MANAGER_START, JSON}},
    {"MacModelLatencyMs", {CLEAR_ON_MANAGER_START, FLOAT}},
    {"MacModelMissRate", {CLEAR_ON_MANAGER_START, FLOAT}},
    {"MacModelPresent", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelReachable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelCompiled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelReady", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelActive", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelFault", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelFailed", {CLEAR_ON_MANAGER_START, BOOL}},
    {"MacModelLastError", {CLEAR_ON_MANAGER_START, STRING}},
    {"MacModelDownloadProgress", {CLEAR_ON_MANAGER_START, FLOAT}},
    {"UsbGpuStatus", {CLEAR_ON_MANAGER_START, JSON}},
    {"UsbGpuLatencyMs", {CLEAR_ON_MANAGER_START, FLOAT}},
    {"UsbGpuActive", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UsbGpuFailed", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UsbGpuPresent", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UsbGpuLastError", {CLEAR_ON_MANAGER_START, STRING}},
    {"UsbGpuSetupProgress", {CLEAR_ON_MANAGER_START, FLOAT}},
    {"UsbGpuCompiled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UsbGpuLoading", {CLEAR_ON_MANAGER_START, BOOL}},

    {"IQDynamicMode", {PERSISTENT, BOOL, "0"}},
    {"IQDynamicBlendStockRadar", {PERSISTENT, BOOL, "0"}},
    {"IQDynamicConditionalCurves", {PERSISTENT, BOOL, "1"}},
    {"IQDynamicConditionalSlowerLead", {PERSISTENT, BOOL, "1"}},
    {"IQDynamicConditionalStoppedLead", {PERSISTENT, BOOL, "1"}},
    {"IQDynamicConditionalModelStops", {PERSISTENT, BOOL, "1"}},
    {"IQDynamicConditionalSLCFallback", {PERSISTENT, BOOL, "1"}},
    {"IQDynamicConditionalSpeed", {PERSISTENT, FLOAT, "18.0"}},
    {"IQDynamicConditionalLeadSpeed", {PERSISTENT, FLOAT, "24.0"}},
    {"IQDynamicModelStopTime", {PERSISTENT, FLOAT, "3.0"}},
    {"IQDynamicMinimumForceStopLength", {PERSISTENT, FLOAT, "0.0"}},
    {"IQForceStops", {PERSISTENT, BOOL, "1"}},
    {"IQCustomStopDistance", {PERSISTENT, INT, "0"}},  // meters, -2..2; negative = stop closer, positive = stop further back; independent of IQForceStops
    {"IQBlindSpotAlerts", {PERSISTENT, BOOL, "0"}},
    {"IQExpandedStatus", {PERSISTENT, BOOL, "0"}},
    {"HomePanelWidget", {PERSISTENT, STRING, "changelog"}},

    // iqpilot model params
    {"CameraOffset", {PERSISTENT, FLOAT, "0.0"}},
    {"IQLiveSteerDelay", {PERSISTENT, BOOL, "1"}},
    {"IQLateralAccelSlew", {PERSISTENT, BOOL, "0"}},
    {"IQLateralCurvatureLookahead", {PERSISTENT, BOOL, "0"}},
    {"IQSoftwareSteerDelay", {PERSISTENT, FLOAT, "0.2"}},
    {"IQSteerDelayCache", {PERSISTENT, FLOAT, "0.2"}},
    {"LaneChangeBsd", {PERSISTENT, INT, "0"}},          // -1 ignore BSD, 0 default, 1 block lane change on BSD
    {"LaneChangeContinuous", {PERSISTENT, BOOL, "0"}},  // 0 one-shot per blinker, 1 chain on held blinker (torque-gated)
    {"LaneChangeDelay", {PERSISTENT, FLOAT, "0.0"}},    // tenths of a second; scaled by 0.1 in desire_helper
    {"LaneChangeNeedTorque", {PERSISTENT, INT, "0"}},   // <0 disable blinker LC, 0 default, >0 require torque
    {"IQLaneTurnDesire", {PERSISTENT, BOOL, "0"}},
    {"IQLaneTurnValue", {PERSISTENT, FLOAT, "19.0"}},
    {"PlanplusControl", {PERSISTENT, FLOAT, "1.0"}},
    {"LatSmoothSec", {PERSISTENT, INT, "13"}},
    {"ModelSmoothingEnabled", {PERSISTENT, BOOL, "0"}},
    {"ModelLatSmoothSec", {PERSISTENT, INT, "0"}},

    // IQ.Pilot Parameters:
    {"ShowBSMIndicators", {PERSISTENT, BOOL, "0"}},
    {"ShowSteeringArc", {PERSISTENT, BOOL, "0"}},
    {"ShowRoadName", {PERSISTENT, BOOL, "0"}},
    {"ShowRealTimeAcceleration", {PERSISTENT, BOOL, "0"}},
    {"ForceSmallUI", {PERSISTENT, BOOL, "0"}},
    {"DeveloperUI", {PERSISTENT, BOOL, "0"}},
    {"OBrightness", {PERSISTENT, BOOL, "0"}},
    {"OBrightnessManual", {PERSISTENT, BOOL, "0"}},
    {"OBrightnessDelay", {PERSISTENT, BOOL, "0"}},
    {"MapAdvisorySpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT}},
    {"MapdVersion", {PERSISTENT, STRING}},
    {"MapdSettings", {PERSISTENT, JSON}},  // pfeiferj/mapd v2 persistent settings (read/written by the mapd binary)
    {"MapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT, "0.0"}},
    {"NextMapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_OSMUpdateRequired", {CLEAR_ON_MANAGER_START, JSON}},
    {"OsmDbUpdatesCheck", {CLEAR_ON_MANAGER_START, BOOL}},  // mapd database update happens with device ON, reset on boot
    {"OSMDownloadBounds", {PERSISTENT, STRING}},
    {"OsmDownloadedDate", {PERSISTENT, STRING, "0.0"}},
    {"OSMDownloadLocations", {PERSISTENT, JSON}},
    {"AthenaNavigationRoute", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationActive", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"NavigationDestination", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationEnabled", {PERSISTENT, BOOL, "0"}},
    {"NavigationDebugFlags", {PERSISTENT, JSON}},
    {"NavigationManeuvers", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationPreferences", {PERSISTENT, JSON}},
    {"NavigationRenderRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"NavigationRecalculateRoutes", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"NavigationRouteAlternatives", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationRouteSelection", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationTrafficRefreshEnabled", {PERSISTENT, BOOL, "1"}},
    {"ScreenRecording", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"OSMDownloadProgress", {CLEAR_ON_MANAGER_START, JSON}},
    {"OfflineTilesDownloadProgress", {CLEAR_ON_MANAGER_START, JSON}},
    {"OfflineTilesDownloadRequest", {PERSISTENT, JSON}},
    {"OsmLocal", {PERSISTENT, BOOL}},
    {"OsmLocationName", {PERSISTENT, STRING}},
    {"OsmLocationTitle", {PERSISTENT, STRING}},
    {"OsmLocationUrl", {PERSISTENT, STRING}},
    {"OsmStateName", {PERSISTENT, STRING, "All"}},
    {"OsmStateTitle", {PERSISTENT, STRING}},
    {"OsmStateNames", {PERSISTENT, JSON}},
    {"OsmWayTest", {PERSISTENT, STRING}},
    {"RoadName", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"IQRoadNameOverlay", {PERSISTENT, BOOL, "0"}},
    {"IQSpeedAssistMode", {PERSISTENT, INT, "1"}},
    {"IQSpeedAssistOffsetType", {PERSISTENT, INT, "0"}},
    {"IQSpeedAssistPolicy", {PERSISTENT, INT, "3"}},
    {"IQSpeedAssistValueOffset", {PERSISTENT, INT, "0"}},
    {"SpeedLimitController", {PERSISTENT, BOOL, "0"}},
    {"ConstructionZoneAssist", {PERSISTENT, BOOL, "0"}},
    {"VisionVehicleTracks", {PERSISTENT, BOOL, "0"}},
    {"AmbientTrackDots", {PERSISTENT, BOOL, "1"}},
    {"EnvironmentView", {PERSISTENT, INT, "0"}},
    {"ConstructionZoneSpeed", {PERSISTENT, INT, "60"}},
    {"ShowSpeedLimits", {PERSISTENT, BOOL, "0"}},
    {"SLCPolicy", {PERSISTENT, INT, "1"}},
    {"SLCAutoConfirm", {PERSISTENT, BOOL, "0"}},
    {"SLCSetSpeedToLimit", {PERSISTENT, BOOL, "0"}},
    {"speed_limit_offset1", {PERSISTENT, FLOAT, "0"}},
    {"speed_limit_offset2", {PERSISTENT, FLOAT, "0"}},
    {"speed_limit_offset3", {PERSISTENT, FLOAT, "0"}},
    {"speed_limit_offset4", {PERSISTENT, FLOAT, "0"}},
    {"speed_limit_offset5", {PERSISTENT, FLOAT, "0"}},
    {"speed_limit_offset6", {PERSISTENT, FLOAT, "0"}},
    {"speed_limit_offset7", {PERSISTENT, FLOAT, "0"}},
    {"SpeedLimitConfirmationHigher", {PERSISTENT, BOOL, "1"}},
    {"SpeedLimitConfirmationLower", {PERSISTENT, BOOL, "0"}},
    {"MapSpeedLookaheadHigher", {PERSISTENT, FLOAT, "5.0"}},
    {"MapSpeedLookaheadLower", {PERSISTENT, FLOAT, "5.0"}},
    {"SLCFallbackExperimentalMode", {PERSISTENT, BOOL, "0"}},
    {"SLCFallbackSetSpeed", {PERSISTENT, BOOL, "0"}},
    {"SLCFallbackPreviousSpeedLimit", {PERSISTENT, BOOL, "1"}},
    {"SLCOverrideMethod", {PERSISTENT, INT, "0"}},
    {"SLCOnlineFiller", {PERSISTENT, BOOL, "0"}},
    {"SLCDataCollection", {PERSISTENT, BOOL, "0"}},
    {"MapBoxRequests", {PERSISTENT, JSON}},
    {"OverpassRequests", {PERSISTENT, JSON}},
    {"SpeedLimits", {PERSISTENT, JSON}},
    {"SpeedLimitsFiltered", {PERSISTENT, JSON}},
    {"PreviousSpeedLimit", {PERSISTENT, FLOAT, "0"}},
    {"UpdateSpeedLimits", {CLEAR_ON_IGNITION_ON}},
    {"UpdateSpeedLimitsStatus", {CLEAR_ON_IGNITION_ON, STRING}},
    {"SLCMapboxSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT, "0"}},
    {"NavigateOnIQPilot", {PERSISTENT, BOOL, "1"}},
    {"NavOnlineTargets", {PERSISTENT, BOOL, "1"}},
    {"NavOfflineFallback", {PERSISTENT, BOOL, "1"}},
    {"NavPreferOfflineSources", {PERSISTENT, BOOL, "0"}},
    {"OfflineRoutingEnabled", {PERSISTENT, BOOL, "1"}},
    {"OfflineRoutingOnly", {PERSISTENT, BOOL, "0"}},
    {"OfflineRoutingHost", {PERSISTENT, STRING, "http://127.0.0.1:8002"}},
    {"EnableCurvatureController", {PERSISTENT, BOOL, "0"}},
    {"EnableSmoothSteer", {PERSISTENT, BOOL, "0"}},
    {"EnableSpeedLimitControl", {PERSISTENT, BOOL, "0"}},
    {"MapCurveSpeedController", {PERSISTENT, BOOL, "0"}},
    {"VisionCurveSpeedController", {PERSISTENT, BOOL, "0"}},
    {"SpeedCameraAlerts", {PERSISTENT, BOOL, "0"}},
    {"RedLightCameraAlerts", {PERSISTENT, BOOL, "0"}},
    {"FlockCameraAlerts", {PERSISTENT, BOOL, "0"}},
    {"SpeedCameraSlowdown", {PERSISTENT, BOOL, "0"}},
    {"SpeedCameraSafetyFactor", {PERSISTENT, FLOAT, "1.0"}},
    {"NavCamerasData", {PERSISTENT, JSON}},
    {"NavCameraRoadGraphData", {PERSISTENT, JSON}},
    {"WazePoliceApiKey", {PERSISTENT | DONT_LOG, STRING}},
    {"WazePoliceAlertMode", {PERSISTENT, INT, "0"}},
    {"WazePoliceShadow", {PERSISTENT, BOOL, "0"}},
    {"EnableLongComfortMode", {PERSISTENT, BOOL, "0"}},
    {"EnableSpeedLimitPredicative", {PERSISTENT, BOOL, "0"}},
    {"EnableSLPredReactToSL", {PERSISTENT, BOOL, "0"}},
    {"EnableSLPredReactToCurves", {PERSISTENT, BOOL, "0"}},
    {"ForceRHDForBSM", {PERSISTENT, BOOL, "0"}},
    {"NavDestination", {PERSISTENT, STRING}},
    {"eBrakeActive", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"Konn3ktAllowOffroadExternalCanTx", {PERSISTENT, BOOL}},
    {"MapboxToken", {PERSISTENT, STRING}},
    {"MapboxTokenQRCode", {PERSISTENT, JSON}},
    {"AmapWebServiceKey", {PERSISTENT, STRING}},
    {"AmapStatus", {CLEAR_ON_MANAGER_START, JSON}},
    {"TomTomToken", {PERSISTENT, STRING}},
    {"UIAccentColor", {PERSISTENT, STRING, "#00FFF5"}},
    {"AngleLateralControl", {PERSISTENT, BOOL}},
    {"ALCTorqueBlend", {PERSISTENT, BOOL}},
};
